import pandas

from src.logger import log


def get_processed_file(file_path):
    df = pandas.read_csv(file_path, dtype={'asatdatestr': str,  # bet cycle date
                                           'asattimestr': str,  # bet cycle time
                                           # These ids probably form a unique composite of some sort
                                           'meetid': str,  # 2 unique ids
                                           'performanceid': str,  # 290 unique ids
                                           'raceid': str,  # 11 unique ids
                                           # Seems to be combo of asatdate+meetid+performanceid+raceid
                                           'refid': str,
                                           'type': str,  # FINAL or INTER, but what does it mean?
                                           # bet type: place, win, quinella and omni.
                                           # Different types allow different bet combinations and accordingly pool dimensions.
                                           'pool': str,
                                           'ccy': str,  # currency: 83% HKD and 17% GBP
                                           # horse number  and bet amount
                                           # is the number of participating horses fixed or variable?
                                           'bet_amount_horse_nb_1': float,
                                           'bet_amount_horse_nb_2': float,
                                           'bet_amount_horse_nb_3': float,
                                           'bet_amount_horse_nb_4': float,
                                           'bet_amount_horse_nb_5': float,
                                           'bet_amount_horse_nb_6': float,
                                           'bet_amount_horse_nb_7': float,
                                           'bet_amount_horse_nb_8': float,
                                           'bet_amount_horse_nb_9': float,
                                           'bet_amount_horse_nb_10': float,
                                           'bet_amount_horse_nb_11': float,
                                           'bet_amount_horse_nb_12': float,
                                           'bet_amount_horse_nb_13': float,
                                           'bet_amount_horse_nb_14': float,
                                           # Composite identifier generated by me
                                           '_id': str,
                                           '_valid': str
                                           })
    log(f'Read in file of {len(df.index)} rows')
    return df